[package]
name = "mwe"
edition = "2024"

[[bin]]
name = "mwe"

[build-dependencies]
cxx-build = "1.0.188"
miette = { version = "5", features = ["fancy"] }

[dependencies]
cxx = { version = "1.0.143", features = ["c++17", "alloc"] }
